openapi: 3.1.0
info:
  version: 1.0.0
  title: my app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    <This is a documentation of contact book>
tags:
  - name: Contacts
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-8-rm4z.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
